version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/server
    environment:
      FLASK_ENV: development
    depends_on:
    - db
  db:
    image: mongo:latest
    hostname: mongo
    environment:
      - MONGO_INITDB_DATABASE=int20h_test_exercise
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
